### ISSUE TITLE
App unable to restore backed up data

### ISSUE THREAD

**Issue by fabianmani** [stovocor/whohasmystuff#34] opened 2018-03-21 09:23 UTC
#### Expected behavior
I expected when i click on the restore back up icon, it should restore my backed up data.

#### Actual behavior
The app shows database error "an error occurred while reading the database file".

#### How to reproduce
* download the app
* add items and who borrowed the items
* backup added items, then try to restore the backed up data..

* Device: Tecno K7
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/TA3rGyofVZ8.
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/app-unable-to-restore-backed-up-data">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stovocor** [comment] 2018-03-21 20:03
Duplicate of #33

**Closed by stovocor** 2018-03-21 20:03 UTC
